const actionTypes = {
	"SET_PAGE": "SET_PAGE",
	"CHANGE_PAGE": "CHANGE_PAGE",
	"SHOW_ARTICLES": "SHOW_ARTICLES",
	"LOGIN":"LOGIN",
	"CREATE_BOOKMARK":"CREATE_BOOKMARK",
	"CREATE_MEMBER":"CREATE_MEMBER",
	"LOAD_PROMOTION_REQUESTS":"LOAD_PROMOTION_REQUESTS",
	"GRANT_PROMOTION_REQUEST":"GRANT_PROMOTION_REQUEST",
	"ANALYZE_ARTICLE":"ANALYZE_ARTICLE",
	"MY_ARTICLE_KEYWORD_SEARCH":"MY_ARTICLE_KEYWORD_SEARCH",
	"SHOW_STREAM":"SHOW_STREAM",
	"REVIEW_ARTICLE":"REVIEW_ARTICLE",
	"ADD_ARTICLE_CRITIQUE":"ADD_ARTICLE_CRITIQUE",
	"FAILED":"FAIL"
};

export default actionTypes;